import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from 'react-icons/ai';
import Image from 'next/image';
import React from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = React.useState<boolean>(false);

  return (
    <div
      className={`${
        darkMode ? 'dark' : ''
      } transition-all duration-[2s] ease-in-out`}
    >
      <Head>
        <title>Rocky Essel</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-gray-300'>
              developedbyed
            </h1>

            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className='cursor-pointer dark:text-gray-300'
                />
              </li>
              <li>
                <a
                  className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-3 rounded-md ml-8'
                  href='#'
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div id='hero-sec' className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>
              Dimitri Marco
            </h2>
            <h3 className='text-2xl py-2 md:text-3xl md:text-xl dark:text-gray-200'>
              Developer and designer.
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-md mx-auto dark:text-gray-300'>
              Freelancer providing services for programming and design content
              needs. Join me down below and let&apos;s get cracking!
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-300'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 m-20 overflow-hidden md:w-96 md:h-96'>
            <Image
              objectFit='cover'
              priority={true}
              layout='fill'
              alt='The '
              src='https://raw.githubusercontent.com/developedbyed/react-portofolio-with-tailwind/main/public/dev-ed-wave.png'
            />
          </div>

          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>
              Since the beginning of my journey as a freelance design and
              developer, I&apos;ve done remote work for
              <span className='text-teal-500'> agencies </span> consulted for
              <span className='text-teal-500'> startups </span> and collaborated
              with talented people to create digital products for both business
              and consumer use.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>
              I offer from a wide range of services, including brand design and
              programming and teaching.
            </p>
          </div>

          <div className='lg:flex gap-10'>
            <div className='text-center flex flex-col items-center shadow-lg p-10 rounded-xl my-10'>
              <Image
                className='text-center'
                width={100}
                height={100}
                alt={``}
                src={
                  'https://raw.githubusercontent.com/developedbyed/react-portofolio-with-tailwind/main/public/design.png'
                }
              />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Beautiful Designs
              </h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core
                design concepts and theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>

            <div className='text-center flex flex-col items-center shadow-lg p-10 rounded-xl my-10'>
              <Image
                className='text-center'
                width={100}
                height={100}
                alt={``}
                src={
                  'https://raw.githubusercontent.com/developedbyed/react-portofolio-with-tailwind/main/public/code.png'
                }
              />
              <h3 className='text-lg font-medium pt-8 pb-2'>Code</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core
                design concepts and theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>

            <div className='text-center flex flex-col items-center shadow-lg p-10 rounded-xl my-10'>
              <Image
                className='text-center'
                width={100}
                height={100}
                alt={``}
                src={
                  'https://raw.githubusercontent.com/developedbyed/react-portofolio-with-tailwind/main/public/consulting.png'
                }
              />
              <h3 className='text-lg font-medium pt-8 pb-2'>Code</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core
                design concepts and theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>
              Since the beginning of my journey as a freelance design and
              developer, I&apos;ve done remote work for
              <span className='text-teal-500'> agencies </span> consulted for
              <span className='text-teal-500'> startups </span> and collaborated
              with talented people to create digital products for both business
              and consumer use.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>
              I offer from a wide range of services, including brand design and
              programming and teaching.
            </p>
          </div>

          <div
            className={`flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap`}
          >
            <div className={`basis-1/4 flex-1`}>
              <Image
                className={`rounded-lg object-cover w-[100%] h-[100%]`}
                priority={true}
                src='https://raw.githubusercontent.com/developedbyed/react-portofolio-with-tailwind/main/public/web1.png'
                width={1000}
                height={1000}
                layout={`responsive`}
                alt=''
              />
            </div>
            <div className={`basis-1/4 flex-1`}>
              <Image
                className={`rounded-lg object-cover w-[100%] h-[100%]`}
                priority={true}
                src='https://raw.githubusercontent.com/developedbyed/react-portofolio-with-tailwind/main/public/web2.png'
                width={1000}
                height={1000}
                layout={`responsive`}
                alt=''
              />
            </div>
            <div className={`basis-1/4 flex-1`}>
              <Image
                className={`rounded-lg object-cover w-[100%] h-[100%]`}
                priority={true}
                src='https://raw.githubusercontent.com/developedbyed/react-portofolio-with-tailwind/main/public/web3.png'
                width={1000}
                height={1000}
                layout={`responsive`}
                alt=''
              />
            </div>
            <div className={`basis-1/4 flex-1`}>
              <Image
                className={`rounded-lg object-cover w-[100%] h-[100%]`}
                priority={true}
                src='https://raw.githubusercontent.com/developedbyed/react-portofolio-with-tailwind/main/public/web4.png'
                width={1000}
                height={1000}
                layout={`responsive`}
                alt=''
              />
            </div>
            <div className={`basis-1/4 flex-1`}>
              <Image
                className={`rounded-lg object-cover w-[100%] h-[100%]`}
                priority={true}
                src='https://raw.githubusercontent.com/developedbyed/react-portofolio-with-tailwind/main/public/web3.png'
                width={1000}
                height={1000}
                layout={`responsive`}
                alt=''
              />
            </div>
            <div className={`basis-1/4 flex-1`}>
              <Image
                className={`rounded-lg object-cover w-[100%] h-[100%]`}
                priority={true}
                src='https://raw.githubusercontent.com/developedbyed/react-portofolio-with-tailwind/main/public/web6.png'
                width={1000}
                height={1000}
                layout={`responsive`}
                alt=''
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

//
