import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from 'react-icons/ai';
import Image from 'next/image';
import React from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = React.useState<boolean>(false);

  return (
    <div
      className={`${
        darkMode ? 'dark' : ''
      } transition-all duration-[2s] ease-in-out`}
    >
      <Head>
        <title>Rocky Essel</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

    </div>
  );
}

//
